budget/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from django.conf.urls import include

from . import views

urlpatterns = [
	path('', views.homeRedirect),
	path('home/', include('dashboard.urls')),
	path('admin/', admin.site.urls),
	path('accounts/', include('django.contrib.auth.urls')),
    path('reset_password/', views.forgottenPassword, name='resetpassword'), 
	path('register/', views.register, name='register'),
    path('password/<tag>', views.generatePassword),
    path('reset_password', views.passwordRedirect),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
    url(r'^password/$', views.changePassword, name='change_password'),
]

dashboard/urls.py
from django.urls import path
from budget import settings
from . import views
from .views import(
    DashboardView,
)
from django.contrib.auth.decorators import login_required
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import pdfs 

app_name = 'dashboard'
urlpatterns = [
	path('', login_required(DashboardView.as_view()), name='index'),
	path('Category/<int:pk>/delete/', views.CategoryDeleteView.as_view(), name='category-delete'),
	path('Entry/<int:pk>/delete/', views.EntryDeleteView.as_view(), name='entry-delete'),
	path('Balance/<int:pk>/delete/', views.BalanceDeleteView.as_view(), name='balance-delete'),
	path('Category/<int:pk>/change/', views.changeStatusCategory, name='category-change'),
	path('Category/<int:pk>/changeall/', views.changeAllStatusCategory, name='category-changeall'),
	path('Balance/<int:pk>/changeall/', views.changeAllStatusBalance, name='balance-changeall'),
	path('Category/reset/', views.categoryStatusReset, name='category-reset'),
	path('Balance/reset/', views.balanceStatusReset, name='balance-reset'),
	path('Enjtry/days3/', views.change3days, name='entry-days3'),
	path('Enjtry/days7/', views.change7days, name='entry-days7'),
	path('Enjtry/days30/', views.changeMonth, name='entry-days30'),
	path('Enjtry/days365/', views.changeYear, name='entry-days365'),
	path('Enjtry/All/', views.ResetEntry, name='entry-resetAll'),
	path('report/', pdfs.generatePDF, name='generate-pdf'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.contrib import admin
from django.core.exceptions import ValidationError
from datetime import date
from django.db.models.signals import post_save

class Chart(models.Model):
	photo = models.ImageField(upload_to="charts/")
	user = models.ForeignKey (
		settings.AUTH_USER_MODEL,
		on_delete=models.CASCADE,
		null = True,
		blank = True,
	)	

class Category(models.Model):
	name = models.CharField(max_length = 120)
	active = models.BooleanField(default=True)
	user = models.ForeignKey (
		settings.AUTH_USER_MODEL,
		on_delete=models.CASCADE,
		null = True,
		blank = True,
	)
	

	
	def __str__(self):
		return self.name 

class Balance(models.Model):
	name = models.CharField(max_length = 120)
	amount = models.DecimalField(max_digits=12, decimal_places=2, default=0)
	active = models.BooleanField(default=True)
	user = models.ForeignKey (
		settings.AUTH_USER_MODEL,
		on_delete=models.CASCADE,
		null = True,
		blank = True,
	)

	def __str__(self):
		return self.name

def no_future(value):
    today = date.today()
    if value > today:
        raise ValidationError('Purchase_Date cannot be in the future.')

class PasswordReset(models.Model): 
	resetLink = models.CharField(max_length = 120)
	user = models.ForeignKey (
		settings.AUTH_USER_MODEL,
		on_delete=models.CASCADE,
		null = True,
		blank = True,
	)

class Entry(models.Model):
    COME_CHOICES = [
        ('income','Income'),
        ('outcome','Outcome')
    ]
    DAYS_CHOICES = [
        ('all','ALL'),
        ('day3','Last3days'),
		('day7','Last7days'),
		('month','LastMonth'),
		('year','LastYear'),
    ]
    type_choice = models.CharField(max_length=120, choices = COME_CHOICES,default="Outcome")
    name = models.CharField(max_length = 120)
    amount = models.DecimalField(max_digits=12, decimal_places =2, default = 0)
    day_filter = models.CharField(max_length=120, choices = DAYS_CHOICES, default='all')
    active_date = models.BooleanField(default=True) 
    date = models.DateField(validators=[no_future]) 
    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
		default= 1,
    )
    balance = models.ForeignKey(
        Balance,
        on_delete=models.CASCADE,
        default= 1,
    )
    user = models.ForeignKey (
		settings.AUTH_USER_MODEL,
		on_delete=models.CASCADE,
		null = True,
		blank = True,
	)
	
    def __str__(self):
        return self.name 

    def save(self, *args, **kwargs):
        if(self.type_choice == "outcome"):
            self.amount = self.amount * -1
        self.balance.amount += self.amount
        self.balance.save()
        super(Entry, self).save(*args, **kwargs)

dashboard/forms.py
from django import forms

from .models import Category, Entry, Balance

class CategoryForm(forms.Form):
	name = forms.CharField(max_length=100)

	def __init__(self, user, *args, **kwargs):
		self.user = user
		super().__init__(*args, **kwargs)

class EntryModelForm(forms.ModelForm):
    COME_CHOICES = [
        ('income','Income'),
        ('outcome','Outcome')
    ]
    type_choice = forms.CharField(widget = forms.RadioSelect(choices = COME_CHOICES))
    date = forms.DateField(
        input_formats=['%d/%m/%Y'],
        widget=forms.DateInput(attrs={
            'class': 'form-control datetimepicker-input',
            'data-target': '#datetimepicker1'
        }))
    amount = forms.DecimalField(min_value = 0,decimal_places=2)
    class Meta:
        model = Entry
        
        fields = [
            'name',
			'amount',
            'category',
			'balance',
            'date',
            'type_choice',
            'active_date',
        ]

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super().__init__(*args, **kwargs)

        self.fields['category'].queryset = self.fields['category'].queryset.filter(
            user = user)
        self.fields['balance'].queryset = self.fields['balance'].queryset.filter(
            user=user)

class BalanceForm(forms.ModelForm):
    class Meta:
        model = Balance
        fields = [
            'name',
			'amount',
        ]

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super().__init__(*args, **kwargs)

dashboard/views.py
from django.shortcuts import render, redirect
from django.views.generic import ( View, DeleteView )
from django.urls import reverse_lazy
from django.db.models import Sum
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from datetime import datetime, timedelta

from .filters import EntryFilter

from . import statistics as sts
from . import timestamps 
from . import charts as chartgen

from .models import Category, Entry, Balance
from .forms import EntryModelForm, CategoryForm, BalanceForm

class DashboardView(View):
	def get(self, request, *args, **kwargs):
		allUserRecords = getUserRecords(request.user)
		recordsByCategory = getCategoriesMap(allUserRecords)

		stats = sts.Statistics().collectStatistics(recordsByCategory, allUserRecords)
		total = getUserBalancesSum(request.user)
		chartgen.generateCategorialChart(recordsByCategory, request) 
		
		categories = Category.objects.filter(user_id = request.user)
		balances = Balance.objects.filter(user_id = request.user)
		entries = Entry.objects.filter(user_id = request.user).filter(category__active=True).filter(balance__active=True).filter(active_date = True)

		firstEntry = Entry.objects.filter(user_id = request.user)[:1]
		formsList = [CategoryForm(request.user), EntryModelForm(request.user), BalanceForm(request.user), PasswordChangeForm(request.user, request.POST)]

		entryFilter = EntryFilter(request.GET, queryset=entries)
		
		return render(request, "homeBlocks.html", 
				{ 'categories': categories, 
				'entry1': firstEntry, 
				'entries': entries,
				'balance': balances, 
				'form': formsList[0], 
				'form2': formsList[1], 
				'form3': formsList[2], 
				'form4': formsList[3], 
				'total': total, 
				'stats': stats, 
				'username': request.user,
				'filter' : entryFilter,
				})

	def post(self, request):
		formsList = [CategoryForm(request.user, request.POST), EntryModelForm(request.user, request.POST), BalanceForm(request.user,request.POST), PasswordChangeForm(request.user, request.POST)]
		
		tstmp = timestamps.Timestamps()

		if Entry.objects.filter(user_id = request.user)[:1]: 
			timeRange = getUserChosenTimestamp(Entry.objects.filter(user_id = request.user)[:1].get()) 
		else: 
			timeRange = 'all' 

		if request.POST.get('actionCat') == "Save":
			if formsList[0].is_valid():
				name = formsList[0].cleaned_data['name']
				Category.objects.create(name = name, user = request.user)
		elif request.POST.get('actionEntry') == "Save":
			if formsList[1].is_valid():
				entry = formsList[1].save(commit = False)
				entry.user = self.request.user

				if(timeRange == 'all'):
					entry.day_filter= 'all'
					entry.active_date = True
				else:
					entry.day_filter = timeRange
					if(entry.date > tstmp.getTimestamp(timeRange)):
						entry.active_date = True 
					else:
						entry.active_date = False 
				
				entry.save()
		elif request.POST.get('actionBalance') == "Save":
			if formsList[2].is_valid():
				balance = formsList[2].save(commit = False)
				balance.user = self.request.user
				balance.save()
		elif request.POST.get('actionchangepassword') == "Save":
			if formsList[3].is_valid():
				user = formsList[3].save()
				update_session_auth_hash(request, formsList[3].user)
				messages.success(request, 'Your password was successfully updated!')
				return redirect('/home/')
			else:
				messages.error(request, 'Please correct the error below.')
		else:
			formsList[3] = PasswordChangeForm(request.user)

		return redirect('/home/')

class CategoryDeleteView(DeleteView):
	model = Category
	success_url = reverse_lazy('dashboard:index')

class EntryDeleteView(DeleteView):
	model = Entry
	success_url = reverse_lazy('dashboard:index')

class BalanceDeleteView(DeleteView):
	model = Balance
	success_url = reverse_lazy('dashboard:index')

def getUserChosenTimestamp(entry):
	timeRange = 'all'
	if entry:
		timeRange = str(entry.day_filter)

	return timeRange

def getUserRecords(user):
	fetchedRecords = []
	for entry in Entry.objects.filter(category__active=True).filter(balance__active=True).filter(active_date=True):
		if entry.user == user:
			fetchedRecords.append(entry)
	
	return fetchedRecords

def getUserBalancesSum(user):
	total = Balance.objects.filter(user=user).aggregate(Sum('amount'))
	if total['amount__sum']:
		total['amount__sum'] = format(total['amount__sum'], '.2f')

	return total

def getCategoriesMap(fetchedRecords):
	recordsByCategory = {}
	for entry in fetchedRecords:
		recordsByCategory[entry.category.name] = 0
			
	for entry in fetchedRecords:
		recordsByCategory[entry.category.name] += entry.amount

	return recordsByCategory 

def changeStatusCategory(request, pk):
	category = Category.objects.get(pk=pk)
	if(category.active == False):
		category.active = True
	else:
		category.active = False
	
	category.save()
	return redirect('/home/')

def change3days(request):
	lastDays3 = datetime.today() - timedelta(days=3)
	Entry.objects.filter(date__gte=lastDays3).filter(user=request.user).update(active_date = True)
	Entry.objects.filter(date__lte=lastDays3).filter(user=request.user).update(active_date = False)
	Entry.objects.filter(user=request.user).update(day_filter = 'day3')

	return redirect('/home/')

def change7days(request):
	lastDays7 = datetime.today() - timedelta(days=7)
	Entry.objects.filter(date__gte=lastDays7).filter(user=request.user).update(active_date = True)
	Entry.objects.filter(date__lte=lastDays7).filter(user=request.user).update(active_date = False)
	Entry.objects.filter(user=request.user).update(day_filter = 'day7')

	return redirect('/home/')

def changeMonth(request):
	lastMonth = datetime.today() - timedelta(days=30)
	Entry.objects.filter(date__gte=lastMonth).filter(user=request.user).update(active_date = True)
	Entry.objects.filter(date__lte=lastMonth).filter(user=request.user).update(active_date = False)
	Entry.objects.filter(user=request.user).update(day_filter = 'month')
	return redirect('/home/')

def changeYear(request):
	lastYear = datetime.today() - timedelta(days=365)
	Entry.objects.filter(date__gte=lastYear).filter(user=request.user).update(active_date = True)
	Entry.objects.filter(date__lte=lastYear).filter(user=request.user).update(active_date = False)
	Entry.objects.filter(user=request.user).update(day_filter = 'year')
	return redirect('/home/')

def ResetEntry(request):
	Entry.objects.filter(user=request.user).update(active_date = True)
	Entry.objects.filter(user=request.user).update(day_filter = 'all')
	return redirect('/home/')

def changeAllStatusCategory(request, pk):
	category = Category.objects.get(pk=pk)
	category2 = Category.objects.filter(user = request.user).filter(active=True)
	if(category.active == True and category2.count() == 1):
		Category.objects.filter(user = request.user).update(active=True)
	else:    
		Category.objects.filter(user = request.user).update(active=False)
		Category.objects.filter(pk = pk).update(active=True)
	return redirect('/home/')

def categoryStatusReset(request):
	Category.objects.filter(user = request.user).update(active = True)
	
	return redirect('/home/')

def changeAllStatusBalance(request, pk):
	balance = Balance.objects.get(pk=pk)
	balance2 = Balance.objects.filter(user = request.user).filter(active=True)
	if(balance.active == True and balance2.count() == 1):
		Balance.objects.filter(user = request.user).update(active=True)
	else:    
		Balance.objects.filter(user = request.user).update(active=False)
		Balance.objects.filter(pk = pk).update(active=True)	

	return redirect('/home/')

def balanceStatusReset(request):
	Balance.objects.filter(user = request.user).update(active = True)

	return redirect('/home/')

dashboard/templates/change_password.html
{% extends 'homeLayout.html' %}
<form method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Save changes</button>
      </form>                                                           

dashboard/templates/homeBlocks.html
{% extends 'homeLayout.html' %}
<!---------------------------------------------Categories Blocks-------------------------------------------------------------------->
{% block categoriesList %}
	{% if categories|length != 0 %}
		{% for instance in categories %}

			<ul class="list-group">
				<li class="list-group-item">
				
					<form action= "{% url 'dashboard:category-change' instance.pk %}" method="POST" style="display: inline" id="categoryList-{{ instance.pk }}">
						{% csrf_token %}
						{% if instance.active == True %}
						<input type="checkbox" checked onclick="document.forms['categoryList-{{ instance.pk }}'].submit();"> {{instance.name}}
						{% else %}
						<input type="checkbox" onclick="document.forms['categoryList-{{ instance.pk }}'].submit();"> {{instance.name}}
						{% endif %}
					</form>
					<button  data-toggle="modal" data-target="#modal-{{ instance.pk }}" class="btn thrash"><i class="fa fa-trash"></i></button>
				</li>
			</ul>
			<div class="modal" id="modal-{{ instance.pk  }}">
					<div class="modal-dialog modal-lg modal-dialog-centered">
						<div class="modal-content">
							<div class="modal-header"style="text-align: center;">
								<h4 class="modal-title">Are you sure you want to delete this category?</h4>
								<button type="button" class="close" data-dismiss="modal">&times;</button>
							</div>

							<div class="modal-body">
								<div class="container-fluid "style="margin-top:15px;overflow-y: auto; text-align: center;"> 
										This action will delete all entries associated with this category.
									<div class=" modal__body">
											
											<form action= "{% url 'dashboard:category-delete' instance.pk %}" method="POST" style="display: inline">
												{% csrf_token %}
												<button type="submit" class="btn btn-secondary">Yes</button>
											</form>
											
											<button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
									</div>	
								</div>
							</div>
						</div>
					</div>
				</div>
			
		{% endfor %}		
	{% else %}
		<ul class="list-group">
				<li class="list-group-item">Nothing to display</li>
			</ul>
	{% endif %}
{% endblock %}

{% block categoryNavbarList %}
	{% if categories|length != 0 %}
		{% for instance in categories %}
		<form action= "{% url 'dashboard:category-changeall' instance.id %}" method="POST" style="display: inline" id = "categoryChangeAll">
			{% csrf_token %}
			<a class="dropdown-item" href="{% url 'dashboard:category-changeall' instance.pk %}">{{instance.name}}</a>
		</form>
		{% endfor %}
			<div class="dropdown-divider"></div>
			<button type="button" class="dropdown-item"  data-toggle="modal" data-target="#addCategory"> Add Category</button>
			<a class="dropdown-item" href="{% url 'dashboard:category-reset'%}">Reset category filters</a>
	{% else %}
        <button type="button" class="dropdown-item"  data-toggle="modal" data-target="#addCategory"> Add Category</button>
		<a class="dropdown-item" href="#">Nothing to display<a>
	{% endif %}
{% endblock %}

{% block categoryForm %}
	<form action='' method='post'>
		{% csrf_token %}
		<table>
			{% for field in form %}
				<tr><td>{{ field.errors }}</td></tr>
				<tr><td>{{ field.label_tag }}</td><td>{{ field }}</td>
			{% endfor %}
			 <tr>
				<td colspan="2"><input class="btn btn-sm btn-primary btn-block btn__style" type="submit" name="actionCat" value="Save" style="margin-top: 15px"/></td>
			</tr>
	 	</table>
	</form>
{% endblock %}
<!---------------------------------------------Entries Blocks-------------------------------------------------------------------->

{%block entry_top_table%}
	{%if entry1.count == 0%}
	<nav class="navbar navbar-default" role="navigation">
			<ul class="nav navbar-tabs" id="myTab" role="tablist">
						<li class="nav-item display__nav active">
							<a class="dropdown-item item__color" href="{% url 'dashboard:entry-resetAll'%}">All</a>
						</li>
						<li class="nav-item display__nav">
							<a class="dropdown-item item__color" href="{% url 'dashboard:entry-days3'%}">Last 3 days</a>
						</li>
						<li class="nav-item display__nav">
							<a class="dropdown-item item__color" href="{% url 'dashboard:entry-days7'%}">Last 7 days</a>
						</li>
						<li class="nav-item display__nav">
							<a class="dropdown-item item__color" href="{% url 'dashboard:entry-days30'%}">Last Month</a>
						</li>
						<li class="nav-item display__nav">
							<a class="dropdown-item item__color" href="{% url 'dashboard:entry-days365'%}">Last Year</a>
						</li>
			</ul>
		</nav>
	{%endif%}
	{% for instance in entry1 %}
		<nav class="navbar navbar-default" role="navigation">
			<ul class="nav navbar-tabs" id="myTab" role="tablist">
						<li class="nav-item display__nav">
							{%if instance.day_filter == 'all'%}
							<a class="dropdown-item item__color "style ="color:#ABA43F;" href="{% url 'dashboard:entry-resetAll'%}">All</a>
							{%else%}
							<a class="dropdown-item item__color" href="{% url 'dashboard:entry-resetAll'%}">All</a>
							{%endif%}
						</li>
						<li class="nav-item display__nav">
							{%if instance.day_filter == 'day3'%}
							<a class="dropdown-item item__color" style ="color:#ABA43F;" href="{% url 'dashboard:entry-days3'%}">Last 3 days</a>
							{%else%}
							<a class="dropdown-item item__color" href="{% url 'dashboard:entry-days3'%}">Last 3 days</a>
							{%endif%}
						</li>
						<li class="nav-item display__nav">
							{%if instance.day_filter == 'day7'%}
							<a class="dropdown-item item__color" style ="color:#ABA43F;" href="{% url 'dashboard:entry-days7'%}">Last 7 days</a>
							{%else%}
							<a class="dropdown-item item__color" href="{% url 'dashboard:entry-days7'%}">Last 7 days</a>
							{%endif%}
						</li>
						<li class="nav-item display__nav">
							{%if instance.day_filter == 'month'%}
							<a class="dropdown-item item__color" style ="color:#ABA43F;" href="{% url 'dashboard:entry-days30'%}">Last Month</a>
							{%else%}
							<a class="dropdown-item item__color" href="{% url 'dashboard:entry-days30'%}">Last Month</a>
							{%endif%}
						</li>
						<li class="nav-item display__nav">
							{%if instance.day_filter == 'year'%}
							<a class="dropdown-item item__color" style ="color:#ABA43F;" href="{% url 'dashboard:entry-days365'%}">Last Year</a>
							{%else%}
							<a class="dropdown-item item__color" href="{% url 'dashboard:entry-days365'%}">Last Year</a>
							{%endif%}
						</li>
			</ul>
		</nav>
	{%endfor %}
{%endblock%}
{% block entriesList %}
	{% if entries|length != 0 %}
		{% for instance in filter.qs %}
		<form action= "{% url 'dashboard:entry-delete' instance.pk %}" method="POST" style="display: inline">
			{% csrf_token %}
			<tr>
					<td>{{instance.date}}</td>
					<td>{{instance.name}}</td>
					<td>{{instance.category}}</td>
					<td>{{instance.amount}}</td>
					<td>{{instance.balance}}</td>
					<td style="text-align:center;"><a data-toggle="modal" href="#modalDelete-{{ instance.pk }}" class="btn thrash"><i class="fa fa-trash"></i></a></td>
			</tr>
		</form>
		<div class="modal" data-keyboard="false" data-backdrop ="static" id="modalDelete-{{ instance.pk }}" >
			<div class="modal-dialog modal-lg modal-dialog-centered">
				<div class="modal-content">
					<div class="modal-header"style="text-align: center;">
						<h4 class="modal-title">Are you sure you want to delete this entry?</h4>
						<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					</div>

					<div class="modal-body">
						<div class="container-fluid "style="margin-top:15px;overflow-y: auto; text-align: center;"> 
								This action can not be undone.
							<div class=" modal__body">
									<form action= "{% url 'dashboard:entry-delete' instance.pk %}" method="POST" style="display: inline">	
										{% csrf_token %}
										<button type="submit" class="btn btn-secondary">Yes</button>
									</form>
									
									<button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
							</div>	
						</div>
					</div>
				</div>
			</div>
		</div>
		{% endfor %}
	{% else %}
	<tr>	
			<td colspan="6">Nothing to display</td>
	</tr>
	{% endif %}
{% endblock %}

{% block entryForm %}
	<form  method='post'>
		{% csrf_token %}
		<table>
			<p>{{form2.name.label_tag}} {{form2.name}}</p>
			<p>{{form2.amount.label_tag}} {{form2.amount}}</p>
			<p>{{form2.type_choice}}</p>
			<p>{{form2.category.label_tag}} {{form2.category}}</p>
			<p>{{form2.balance.label_tag}} {{form2.balance}}</p>
			<p style ="margin-bottom:10px;">Date:</p>
			<div class="input-group date" id="datetimepicker1" data-target-input="nearest">
				{{form2.errors}}
				{{ form2.date }}
				<div class="input-group-append" data-target="#datetimepicker1" data-toggle="datetimepicker">
				  <div class="input-group-text"><i class="fa fa-calendar"></i></div>
				</div>
			  </div>
			  
			  <script>
				$(function () {
				  $("#datetimepicker1").datetimepicker({
					format: 'DD/MM/YYYY',
				  });
				});
			  </script>
			  
			 <tr>
				<td colspan="2"><input class="btn btn-sm btn-primary btn-block btn__style" type="submit" name="actionEntry" value="Save" style="margin-top: 15px"></td>
			</tr>
	 	</table>
	</form>
{% endblock %}
<!---------------------------------------------Balance Blocks-------------------------------------------------------------------->
{% block balanceForm %}
	<form action='' method='post'>
		{% csrf_token %}
		<table>
			{% for field in form3 %}
				<tr><td>{{ field.errors }}</td></tr>
				<tr><td>{{ field.label_tag }}</td><td>{{ field }}</td>
			{% endfor %}
			 <tr>
				<td colspan="2"><input class="btn btn-sm btn-primary btn-block btn__style" type="submit" name="actionBalance" value="Save" style="margin-top: 15px"/></td>
			</tr>
	 	</table>
	</form>
{% endblock %}

{% block balanceList %}
	{% if balance|length != 0 %}
		{% for instance in balance %}
		<form action= "{% url 'dashboard:balance-changeall' instance.pk %}" method="POST" style="display: inline">
			{% csrf_token %}
			<a class="dropdown-item" href="{% url 'dashboard:balance-changeall' instance.pk %}">{{instance.name}}</a>
		</form>
		
		{% endfor %}
		<div class="dropdown-divider"></div>
		<a data-toggle="modal" class="dropdown-item" href="#editBalance" >Manage Balances</a>
		<a class="dropdown-item" href="{% url 'dashboard:balance-reset' %}">Reset balance filters</a>
	{% else %}
		<a class="dropdown-item" href="#">Nothing to display<a>
		<div class="dropdown-divider"></div>
		<a data-toggle="modal" class="dropdown-item" href="#editBalance" >Manage Balances</a>
	{% endif %}
{% endblock %}

{% block balanceModalList%}
	{% if balance|length != 0 %}
		{% for instance in balance %}
		<form action= "{% url 'dashboard:balance-delete' instance.pk %}" method="POST" style="display: inline">
			{% csrf_token %}
			<tr>
				
				<td>{{instance.name}}</td>
				<td>{{instance.amount}}</td>
				<td><a data-toggle="modal" href="#modalBalance-{{ instance.pk }}" class="btn thrash"><i class="fa fa-trash"></i></a></td>
			
	   		</tr>
		</form>
		<div class="modal" data-keyboard="false" data-backdrop ="static" id="modalBalance-{{ instance.pk }}" >
				<div class="modal-dialog modal-lg modal-dialog-centered">
					<div class="modal-content">
						<div class="modal-header"style="text-align: center;">
							<h4 class="modal-title">Are you sure you want to delete this balance?</h4>
							<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
						</div>

						<div class="modal-body">
							<div class="container-fluid "style="margin-top:15px;overflow-y: auto; text-align: center;"> 
									This action will delete all entries associated with this balance.
								<div class=" modal__body">
										<form action= "{% url 'dashboard:balance-delete' instance.pk %}" method="POST" style="display: inline">
											{% csrf_token %}
											<button type="submit" class="btn btn-secondary">Yes</button>
										</form>
										
										<button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
								</div>	
							</div>
						</div>
					</div>
				</div>
			</div>
		{% endfor %}
	{% else %}
		<a class="dropdown-item" href="#">Nothing to display<a>
	{% endif %}
{% endblock %}

{% block totalBalance %}
	{{ total.amount__sum }}
{% endblock %} 


{% block changePassword %}
<div class="form-fields">
		<form method="post" >
		   {% csrf_token %}
		  <table>
			  {% for field in form4 %}
			  <tr><td>{{ field.label_tag }}</td><td>{{ field }}</td>
			  {%endfor%}
			   <tr>
				  <td colspan="2"><input class="btn btn-lg btn-primary btn-block btn__style" type="submit" name="actionchangepassword" value="Save" style="margin-top: 15px"/></td>
			  </tr>
		   </table>
	   </form>
	  </div>                                                        
 {% endblock %}

dashboard/templates/loginLayout.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		{% load static %}
		<link rel="stylesheet" type="text/css" href="{% static 'dashboard/bootstrap.min.css'%}">
		<link rel="stylesheet" type="text/css" href="{% static 'dashboard/login.css'%}">
		<link rel="stylesheet" href="{% static 'dashboard/fontello/css/fontello.css'%}">
		<title>Log in</title>
		<meta name="viewport" content="width=device-width, initial-scale-1">
	</head>
	<body>
		{%block login%}{%endblock%}
		{%block logout%}{%endblock%}
	</body>
</html>